# Generated by Django 3.2.20 on 2023-08-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextendedprofile',
            name='hubspot_contact_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
