# Generated by Django 3.2.20 on 2023-08-30 07:48

from django.db import migrations, models
import openedx.core.djangoapps.xmodule_django.models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_data__default_rate_limit_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', openedx.core.djangoapps.xmodule_django.models.CourseKeyField(db_index=True, max_length=255, primary_key=True, serialize=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_grades', models.BooleanField(default=True)),
                ('enable_enrollment_email', models.BooleanField(default=True)),
                ('auto_enroll', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('course_short_id', models.IntegerField(unique=True)),
                ('seo_tags', models.TextField(blank=True, null=True)),
                ('course_open_date', models.DateTimeField(null=True)),
                ('is_mini_lesson', models.BooleanField(default=False)),
            ],
        ),
    ]
